version: "3.8"

services:
  next-prod:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      DATABASE_URL: "postgresql://user:userpass@db:5432/userdb?schema=public"
      NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
      WEBSITE_URL: ${WEBSITE_URL}
      NEXT_PUBLIC_WEBSITE_URL: ${NEXT_PUBLIC_WEBSITE_URL}
      SECURE_COOKIES: "true"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: userdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
